version: "3.9"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=InfinityStory
    ports:
      - "5432:5432"

  web:
    build: ./API
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MODEL=${MODEL}
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_db:
    driver: local
